
const data = [
  {
    username:"Michael",
    id: 1,
    first_name: 'Justin',
    last_name: 'Armstrong',
    email:"fakeemail@gmail.com",
    phone:'555-555-5555',
    is_admin:0,
    airport:'My airport: Denver',
    trip:'true',
    trip_destination:"Destination: Paris",
    airline:"Airline: SouthWest",
    departure: "Departure: 7:30",
    children:"Children in party: 1",
    flight_msg:"Upcoming Trips:",
    message:"No Trips Scheduled",
    no_trip:"",
    del:"Delete Trip",
    arr:"Arriving",
 
    
  },
  {
    username: "Jack",
    id: 2,
     first_name: 'Thor',
    last_name: 'Thunder',
    email:'fakeeamil@gmail.com',
    phone:'555-555-5555',
    is_admin:0,
    airport: "Orlando",
    trip:"false", 
    message:"No Trips Scheduled",
    no_trip:"",
    del:"Delete Trip",
    arr:"Arriving",

  },
  {  username:"Alex",
    id: 3,
    first_name: 'Captain America',
    last_name: 'Liberty',
    email:"fakeemail@gmail.com",
    phone:'555-555-555',
    is_admin:'false',
    airport: "Philadelphia",
    trip: 'true',
    trip_destination:"Arizona",
    airline: "United",
    departure: "4:01",
     children:"Children in party: 7",
     flight_msg:"Upcoming trips",
    message:"No Trips Scheduled",
    no_trip:"",
    del:"Delete Trip",
    arr:"Arriving",
  },
  {   username:"Colton",
    id: 4,
    first_name: 'Spiderman',
    last_name: 'Wallcrawler',
    email:"fakeemail@gmail.com",
    phone:'555-555-5555',
      is_admin:'false',
    airport: "Texas",
    trip:"true",
    trip_destination:"New York",
    airline: "SouthWest",
    departure: "5:00",
    children: "Children in party: 4",
    flight_msg:"Upcoming trips",
    message:"No Trips Scheduled",
    no_trip:"",
    del:"Delete Trip",
    arr:"Arriving",

  },
  {   username:"Brad",
    id: 5,
    first_name: 'Hulk',
    last_name: 'Big guy',
    email:"fakeemail@gmail.com",
      phone:'555-555-5555',
    is_admin:'false',
    airport: "Denver",
    trip: 'true',
    trip_destination:"Tallahassee",
    airline: "Blue",
    departure: "6:10",
    children: "Children in part: 2",
    flight_msg:"Upcoming trips",
    message:"No Trips Scheduled",
    no_trip:"",
    del:"Delete Trip",
    arr:"Arriving",
  },
  {username:"Ben",
    id: 6,
    first_name: 'Black Widow',
    last_name: 'Super',
    email:"fakeemail@gmail.com",
       phone:'555-555-5555',
    is_admin:'false',
    airport: "Orlando",
    trip:'true',
    trip_destination:"Mumbai",
     airline: "SouthWest",
    departure: "4:35",
    children: 1,
    flight_msg:"Upcoming trips",
    message:"No Trips Scheduled",
    no_trip:"",
    del:"Delete Trip",
    arr:"Arriving",
  },
  {username:"Dennis",
    id: 7,
    first_name: 'The Vision',
    last_name: 'Android',
    email:"fakeemail@gmail.com",
    phone:'555-555-5555',
    is_admin:0,
    airport: 'Illinois',
    trip:'true',
    trip_destination:"Ireland",
    airline: "BelAir",
    departure: "10:00",
    children: "Children in party: 8",
    flight_msg:"Upcoming trips",
    message:"No Trips Scheduled",
    no_trip:"",
    del:"Delete Trip",
    arr:"Arriving",
  },
  {   username:"Jackson",
    id: 8,
    first_name: 'Black Panter',
    last_name: 'Childs',
    email:"fakeemail@gmail.com",
    phone:'555-555-5550',
    is_admin:'false',
    airport: "Illinois",
    trip:'true',
    trip_destination:"Jacksonville",
    airline: "SouthWest",
    departure: "8:00",
    children: "Children in party: 1",
    flight_msg:"Upcoming trips",
    message:"No Trips Scheduled",
    no_trip:"",
    del:"Delete Trip",
    arr:"Arriving",
  },
  {  username:"Teddy",
    id: 9,
    first_name: 'Doctor Strange',
     last_name: 'Jackson',
    email:"fakeemail@gmail.com",
    phone:'555-555-5555',
    is_admin:'false',
    airport:"Colorado",
    trip:'false',
    message:"No Trips Scheduled",
    no_trip:"",
    del:"Delete Trip",
    arr:"Arriving",

  }
];



export default data