
const data = [
  {
    username:"Michael",
    id: 1,
    first_name: 'Justin',
    last_name: 'Armstrong',
    email:"fakeemail@gmail.com",
    phone:'555-555-5555',
    is_admin:0,
    airport:'Denver',
    trip:'true',
  },
  {
    id: 2,
     first_name: 'Thor',
    last_name: 'Thunder',
    email:'fakeeamil@gmail.com',
    phone:'555-555-5555',
    is_admin:0,
    airport: "Orlando",
    trip:"false", 
    message:"No Trips Scheduled",

  },
  {
    id: 3,
    first_name: 'Captain America',
    last_name: 'Liberty',
    email:"fakeemail@gmail.com",
    phone:'555-555-555',
    is_admin:'false',
    airport: "Philadelphia",
    trip: 'true',
    trip_destination:"Arizona",
  },
  {
    id: 4,
    first_name: 'Spiderman',
    last_name: 'Wallcrawler',
    email:"fakeemail@gmail.com",
    phone:'555-555-5555',
        is_admin:'false',
    airport: "Texas",
    trip:"true",
    trip_destination:"New York",
    airline: "SouthWest",
    departure: "5:00",
    children: 4,
    flight_msg:"Upcoming trips",
    Del: "Delete Trip",
    Arriving_msg:"I'm here",

  },
  {
    id: 5,
    first_name: 'Hulk',
    last_name: 'Big guy',
    email:"fakeemail@gmail.com",
      phone:'555-555-5555',
    is_admin:'false',
    airport: "Denver",
    trip: 'true',
    trip_destination:"Tallahassee"
  },
  {
    id: 6,
    first_name: 'Black Widow',
    last_name: 'Super',
    emai:"fakeemail@gmail.com",
       phone:'555-555-5555',
    is_admin:'false',
    airport: "Orlando",
    trip:'true',
    trip_destination:"Jelly",
  },
  {
    id: 7,
    first_name: 'The Vision',
    last_name: 'Android',
    email:"fakeemail@gmail.com",
    phone:'555-555-5555',
    is_admin:0,
    airport: 'Illinois',
    trip:'true',
    trip_destination:"Ireland",
  },
  {
    id: 8,
    first_name: 'Black Panter',
    last_name: 'Childs',
    email:"fakeemail@gmail.com",
    phone:'555-555-5550',
    is_admin:'false',
    airport: "Illinois",
    trip:'true',
    trip_destination:"Jacksonville",
  },
  {
    id: 9,
    first_name: 'Doctor Strange',
  last_name: 'Jackson',
    email:"fakeemail@gmail.com",
    phone:'555-555-5555',
    is_admin:'false',
    airport:"Colorado",
    trip:'true',
    trip_destination:"Naples",

  }
];


export default data